// File generated by FlutterFire CLI.
// Run: flutterfire configure --project=cleanmacfordevs
// to regenerate this file with real values.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for '
          '${defaultTargetPlatform.name}. '
          'Run flutterfire configure to set this up.',
        );
    }
  }

  // Replace placeholder values by running:
  // flutterfire configure --project=cleanmacfordevs
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY',
    appId: '1:REPLACE:web:REPLACE',
    messagingSenderId: 'REPLACE',
    projectId: 'cleanmacfordevs',
    authDomain: 'cleanmacfordevs.firebaseapp.com',
    storageBucket: 'cleanmacfordevs.firebasestorage.app',
    measurementId: 'G-REPLACE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY',
    appId: '1:REPLACE:android:REPLACE',
    messagingSenderId: 'REPLACE',
    projectId: 'cleanmacfordevs',
    storageBucket: 'cleanmacfordevs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY',
    appId: '1:REPLACE:ios:REPLACE',
    messagingSenderId: 'REPLACE',
    projectId: 'cleanmacfordevs',
    storageBucket: 'cleanmacfordevs.firebasestorage.app',
    iosBundleId: 'com.andre.cleanMacForDevsWebPage',
  );
}
